version: '3.8'

services:


  backend:
   
    build: ./backend
    
    container_name: circular_economy_backend
    
    ports:
      - "3000:3000"
    
    volumes:
      
      - ./backend:/app
      
      - /app/node_modules
    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    
    depends_on:
      - postgres

  
  frontend:
    build: ./frontend
    container_name: circular_economy_frontend

    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  
  postgres:
    image: postgres:14-alpine
    container_name: circular_economy_postgres
    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - "5432:5432"
    
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  
  postgres-data: