


POST http://localhost:3000/formularios
Content-Type: application/json

{
    "nome": "henrique",
    "email": "hcm@cin.ufpe.br",
    "mensagem": "Teste de envio de email Nodemailer",
    "data_envio": "2023-10-01T12:00:00Z"
}

###

GET http://localhost:3000/formularios

###

GET http://localhost:3000/formularios/3

###
PUT http://localhost:3000/formularios/3
Content-Type: application/json

{
    "nome": "henrique",
    "email": "hcm@cin.ufpe.br",
    "mensagem": "Mensagem editada"
}

###
DELETE http://localhost:3000/formularios/1