


POST http://localhost:3000/formularios
Content-Type: application/json

{
    "nome": "henrique",
    "email": "hcm@cin.br",
    "mensagem": "estou enviando um email 2 de teste"

}

###

GET http://localhost:3000/formularios

###

GET http://localhost:3000/formularios/3

###
PUT http://localhost:3000/formularios/3
Content-Type: application/json

{
    "nome": "henrique",
    "email": "hcm@cin.br",
    "mensagem": "Mensagem editada"
}

###
DELETE http://localhost:3000/formularios/1